### ISSUE TITLE
transport closed before response received error

### ISSUE THREAD

**Issue by binocarlos** [binocarlos/powerstrip-weave#2]
Hey, I'm having a little trouble connecting via powerstrip - here is what I did:
- built the powerstrip container from the latest `socket-support-protocol-tweaks-and-versioning` branch
- run a powerstrip-debug container which simply logs any requests to stdout before returning
- create the following powerstrip config:

``` yaml
endpoints:
  "/*/containers/create":
    pre: [debug]
  "/*/containers/*/start":
    post: [debug]
plugins:
  debug: http://debug/v1/extension
```
- start powerstrip:

``` bash
$ docker run -d --name powerstrip \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/powerstrip-demo/plugins.yml:/etc/powerstrip/plugins.yml \
  --link powerstrip-debug:debug \
  -p 2375:2375 \
  clusterhq/powerstrip
```
- edit DOCKER_HOST

``` bash
$ export DOCKER_HOST=localhost:2375
```
- do a docker run against powerstrip

``` bash
$ docker run --rm ubuntu bash -c "echo hello"
```

I get the following error when doing this:

```
FATA[0000] Post http://127.0.0.1:2375/v1.16/containers/create: net/http: transport closed before response was received. Are you trying to connect to a TLS-enabled daemon without TLS?
```

There is nothing logged from the debugger container so I don't think the request is making it that far.

Am a bit stuck - sorry if this is something obvious - any clues?

Thanks
